// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ButtonStd = require("../Widgets/ButtonStd.bs.js");

function ContentTableSeating(Props) {
  var isLandscape = Props.isLandscape;
  return React.createElement(React.Fragment, undefined, React.createElement(ButtonStd.make, {
                  isLandscape: isLandscape,
                  label: "N"
                }), React.createElement(ButtonStd.make, {
                  isLandscape: isLandscape,
                  label: "E"
                }), React.createElement(ButtonStd.make, {
                  isLandscape: isLandscape,
                  label: "S"
                }), React.createElement(ButtonStd.make, {
                  isLandscape: isLandscape,
                  label: "W"
                }), React.createElement(ButtonStd.make, {
                  isLandscape: isLandscape,
                  label: "X"
                }), React.createElement(ButtonStd.make, {
                  isLandscape: isLandscape,
                  label: "Y"
                }), React.createElement(ButtonStd.make, {
                  isLandscape: isLandscape,
                  label: "Z"
                }), React.createElement(ButtonStd.make, {
                  isLandscape: isLandscape,
                  label: "N"
                }), React.createElement(ButtonStd.make, {
                  isLandscape: isLandscape,
                  label: "E"
                }), React.createElement(ButtonStd.make, {
                  isLandscape: isLandscape,
                  label: "S"
                }), React.createElement(ButtonStd.make, {
                  isLandscape: isLandscape,
                  label: "W"
                }), React.createElement(ButtonStd.make, {
                  isLandscape: isLandscape,
                  label: "X"
                }), React.createElement(ButtonStd.make, {
                  isLandscape: isLandscape,
                  label: "Y"
                }), React.createElement(ButtonStd.make, {
                  isLandscape: isLandscape,
                  label: "Z"
                }), React.createElement(ButtonStd.make, {
                  isLandscape: isLandscape,
                  label: "N"
                }), React.createElement(ButtonStd.make, {
                  isLandscape: isLandscape,
                  label: "E"
                }), React.createElement(ButtonStd.make, {
                  isLandscape: isLandscape,
                  label: "S"
                }), React.createElement(ButtonStd.make, {
                  isLandscape: isLandscape,
                  label: "W"
                }), React.createElement(ButtonStd.make, {
                  isLandscape: isLandscape,
                  label: "X"
                }), React.createElement(ButtonStd.make, {
                  isLandscape: isLandscape,
                  label: "Y"
                }), React.createElement(ButtonStd.make, {
                  isLandscape: isLandscape,
                  label: "Z"
                }), React.createElement(ButtonStd.make, {
                  isLandscape: isLandscape,
                  label: "N"
                }), React.createElement(ButtonStd.make, {
                  isLandscape: isLandscape,
                  label: "E"
                }), React.createElement(ButtonStd.make, {
                  isLandscape: isLandscape,
                  label: "S"
                }), React.createElement(ButtonStd.make, {
                  isLandscape: isLandscape,
                  label: "W"
                }), React.createElement(ButtonStd.make, {
                  isLandscape: isLandscape,
                  label: "X"
                }), React.createElement(ButtonStd.make, {
                  isLandscape: isLandscape,
                  label: "Y"
                }), React.createElement(ButtonStd.make, {
                  isLandscape: isLandscape,
                  label: "Z"
                }), React.createElement(ButtonStd.make, {
                  isLandscape: isLandscape,
                  label: "N"
                }), React.createElement(ButtonStd.make, {
                  isLandscape: isLandscape,
                  label: "E"
                }), React.createElement(ButtonStd.make, {
                  isLandscape: isLandscape,
                  label: "S"
                }), React.createElement(ButtonStd.make, {
                  isLandscape: isLandscape,
                  label: "W"
                }), React.createElement(ButtonStd.make, {
                  isLandscape: isLandscape,
                  label: "X"
                }), React.createElement(ButtonStd.make, {
                  isLandscape: isLandscape,
                  label: "Y"
                }), React.createElement(ButtonStd.make, {
                  isLandscape: isLandscape,
                  label: "Z"
                }), React.createElement(ButtonStd.make, {
                  isLandscape: isLandscape,
                  label: "N"
                }), React.createElement(ButtonStd.make, {
                  isLandscape: isLandscape,
                  label: "E"
                }), React.createElement(ButtonStd.make, {
                  isLandscape: isLandscape,
                  label: "S"
                }), React.createElement(ButtonStd.make, {
                  isLandscape: isLandscape,
                  label: "W"
                }), React.createElement(ButtonStd.make, {
                  isLandscape: isLandscape,
                  label: "X"
                }), React.createElement(ButtonStd.make, {
                  isLandscape: isLandscape,
                  label: "Y"
                }), React.createElement(ButtonStd.make, {
                  isLandscape: isLandscape,
                  label: "Z"
                }), React.createElement(ButtonStd.make, {
                  isLandscape: isLandscape,
                  label: "N"
                }), React.createElement(ButtonStd.make, {
                  isLandscape: isLandscape,
                  label: "E"
                }), React.createElement(ButtonStd.make, {
                  isLandscape: isLandscape,
                  label: "S"
                }), React.createElement(ButtonStd.make, {
                  isLandscape: isLandscape,
                  label: "W"
                }), React.createElement(ButtonStd.make, {
                  isLandscape: isLandscape,
                  label: "X"
                }), React.createElement(ButtonStd.make, {
                  isLandscape: isLandscape,
                  label: "Y"
                }), React.createElement(ButtonStd.make, {
                  isLandscape: isLandscape,
                  label: "Z"
                }), React.createElement(ButtonStd.make, {
                  isLandscape: isLandscape,
                  label: "N"
                }), React.createElement(ButtonStd.make, {
                  isLandscape: isLandscape,
                  label: "E"
                }), React.createElement(ButtonStd.make, {
                  isLandscape: isLandscape,
                  label: "S"
                }), React.createElement(ButtonStd.make, {
                  isLandscape: isLandscape,
                  label: "W"
                }), React.createElement(ButtonStd.make, {
                  isLandscape: isLandscape,
                  label: "X"
                }), React.createElement(ButtonStd.make, {
                  isLandscape: isLandscape,
                  label: "Y"
                }), React.createElement(ButtonStd.make, {
                  isLandscape: isLandscape,
                  label: "Z"
                }), React.createElement(ButtonStd.make, {
                  isLandscape: isLandscape,
                  label: "N"
                }), React.createElement(ButtonStd.make, {
                  isLandscape: isLandscape,
                  label: "E"
                }), React.createElement(ButtonStd.make, {
                  isLandscape: isLandscape,
                  label: "S"
                }), React.createElement(ButtonStd.make, {
                  isLandscape: isLandscape,
                  label: "W"
                }), React.createElement(ButtonStd.make, {
                  isLandscape: isLandscape,
                  label: "X"
                }), React.createElement(ButtonStd.make, {
                  isLandscape: isLandscape,
                  label: "Y"
                }), React.createElement(ButtonStd.make, {
                  isLandscape: isLandscape,
                  label: "Z"
                }));
}

var make = ContentTableSeating;

exports.make = make;
/* react Not a pure module */
