// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ButtonStd = require("../Widgets/ButtonStd.bs.js");

function ContentTableSeating(Props) {
  var isLandscape = Props.isLandscape;
  return React.createElement(React.Fragment, undefined, React.createElement(ButtonStd.make, {
                  isLandscape: isLandscape,
                  label: "Join",
                  id: "connect"
                }), React.createElement(ButtonStd.make, {
                  isLandscape: isLandscape,
                  label: "Leave",
                  id: "disconnect"
                }), React.createElement("div", undefined, "Hello Table Seating"), React.createElement("table", {
                  style: {
                    border: "0px solid black",
                    borderCollapse: "collapse",
                    margin: "auto"
                  }
                }, React.createElement("thead", undefined), React.createElement("tbody", undefined, React.createElement("tr", {
                          style: {
                            backgroundColor: "#f8f8f8",
                            color: "#000000"
                          }
                        }, React.createElement("td", {
                              style: {
                                border: "0px solid red",
                                borderCollapse: "collapse",
                                margin: "0vh",
                                padding: "0vh 0vh 0vh 0vh"
                              }
                            }, React.createElement(ButtonStd.make, {
                                  isLandscape: isLandscape,
                                  label: "N",
                                  id: "x"
                                })), React.createElement("td", {
                              style: {
                                border: "0px solid red",
                                borderCollapse: "collapse",
                                margin: "0vh",
                                padding: "0vh 0vh 0vh 0vh"
                              }
                            }, React.createElement(ButtonStd.make, {
                                  isLandscape: isLandscape,
                                  label: "E",
                                  id: "x"
                                })), React.createElement("td", {
                              style: {
                                border: "0px solid red",
                                borderCollapse: "collapse",
                                margin: "0vh",
                                padding: "0vh 0vh 0vh 0vh"
                              }
                            }, React.createElement(ButtonStd.make, {
                                  isLandscape: isLandscape,
                                  label: "S",
                                  id: "x"
                                })), React.createElement("td", {
                              style: {
                                border: "0px solid red",
                                borderCollapse: "collapse",
                                margin: "0vh",
                                padding: "0vh 0vh 0vh 0vh"
                              }
                            }, React.createElement(ButtonStd.make, {
                                  isLandscape: isLandscape,
                                  label: "W",
                                  id: "x"
                                })), React.createElement("td", {
                              style: {
                                border: "0px solid red",
                                borderCollapse: "collapse",
                                margin: "0vh",
                                padding: "0vh 0vh 0vh 0vh"
                              }
                            }, React.createElement(ButtonStd.make, {
                                  isLandscape: isLandscape,
                                  label: "X",
                                  id: "x"
                                })), React.createElement("td", {
                              style: {
                                border: "0px solid red",
                                borderCollapse: "collapse",
                                margin: "0vh",
                                padding: "0vh 0vh 0vh 0vh"
                              }
                            }, React.createElement(ButtonStd.make, {
                                  isLandscape: isLandscape,
                                  label: "Y",
                                  id: "x"
                                })), React.createElement("td", {
                              style: {
                                border: "0px solid red",
                                borderCollapse: "collapse",
                                margin: "0vh",
                                padding: "0vh 0vh 0vh 0vh"
                              }
                            }, React.createElement(ButtonStd.make, {
                                  isLandscape: isLandscape,
                                  label: "Z",
                                  id: "x"
                                }))))));
}

var make = ContentTableSeating;

exports.make = make;
/* react Not a pure module */
