// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function getPercentVhTrueAsString(percentAsFloat, vhTrue) {
  return (percentAsFloat * vhTrue).toFixed(0) + "px";
}

exports.getPercentVhTrueAsString = getPercentVhTrueAsString;
/* No side effect */
