// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Ute = require("../Modules/Ute.bs.js");
var React = require("react");
var ContentTableSeating = require("../RegionsContent/ContentTableSeating.bs.js");

function RegionTableSeating(Props) {
  var isLandscape = Props.isLandscape;
  var vhTrue = Props.vhTrue;
  var style = {
    background: "#f8f8f8",
    bottom: isLandscape ? "60%" : "100vw",
    color: "gray",
    left: isLandscape ? Ute.getPercentVhTrueAsString(100.0, vhTrue) : "54%",
    overflowY: "auto",
    position: "fixed",
    right: "0",
    textAlign: "center",
    top: "0"
  };
  return React.createElement("div", {
              style: style
            }, React.createElement(ContentTableSeating.make, {
                  isLandscape: isLandscape
                }));
}

var make = RegionTableSeating;

exports.make = make;
/* react Not a pure module */
