// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Ute = require("../Modules/Ute.bs.js");
var React = require("react");
var ContentScoreSheet = require("../RegionsContent/ContentScoreSheet.bs.js");

function RegionScoreSheet(Props) {
  var isLandscape = Props.isLandscape;
  var vhTrue = Props.vhTrue;
  var style = {
    background: "#e0e0e0",
    bottom: isLandscape ? "0" : "100vw",
    color: "gray",
    left: isLandscape ? Ute.getPercentVhTrueAsString(100.0, vhTrue) : "0",
    overflowY: "auto",
    position: "fixed",
    right: isLandscape ? "0" : "46%",
    textAlign: "center",
    top: isLandscape ? "40%" : "0"
  };
  return React.createElement("div", {
              style: style
            }, React.createElement(ContentScoreSheet.make, {
                  isLandscape: isLandscape
                }));
}

var make = RegionScoreSheet;

exports.make = make;
/* react Not a pure module */
