// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Ute = require("../Modules/Ute.bs.js");
var React = require("react");

function getStyle(isLandscape, vhTrue) {
  if (isLandscape) {
    return {
            backgroundColor: "#fff0d0",
            height: Ute.getPercentVhTrueAsString(17.0, vhTrue),
            left: Ute.getPercentVhTrueAsString(19.0, vhTrue),
            padding: "0vh 0vh 0vh 0vh",
            position: "fixed",
            top: Ute.getPercentVhTrueAsString(58.0, vhTrue),
            width: Ute.getPercentVhTrueAsString(58.0, vhTrue),
            zIndex: "1",
            borderRadius: "10px"
          };
  } else {
    return {
            backgroundColor: "#fff0d0",
            bottom: "25vw",
            height: "17vw",
            left: "19vw",
            padding: "0vh 0vh 0vh 0vh",
            position: "fixed",
            width: "58vw",
            zIndex: "1",
            borderRadius: "10px"
          };
  }
}

function RegionBiddingKeyboard(Props) {
  var isLandscape = Props.isLandscape;
  var vhTrue = Props.vhTrue;
  var style = getStyle(isLandscape, vhTrue);
  return React.createElement("div", {
              style: style
            }, "Hello Bidding Keyboard");
}

var make = RegionBiddingKeyboard;

exports.getStyle = getStyle;
exports.make = make;
/* react Not a pure module */
