// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

console.log("Hello, World!");

function Demo(Props) {
  return React.createElement("div", undefined, "Hello World");
}

var make = Demo;

exports.make = make;
/*  Not a pure module */
