// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

console.log("Hello, World!");

function Demo(Props) {
  return React.createElement("div", undefined, "Hello World");
}

var make = Demo;

export {
  make ,
  
}
/*  Not a pure module */
